<?php

declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260818170000 extends AbstractMigration
{
    public function getDescription(): string { return 'Cria parâmetros globais/institucionais e sua auditoria'; }
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE parametros_sistema (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, instituicao_id INT DEFAULT NULL, escopo VARCHAR(20) NOT NULL, chave_escopo VARCHAR(50) NOT NULL, limite_upload_mb INT NOT NULL, notificacao_interna BOOLEAN DEFAULT true NOT NULL, notificacao_email BOOLEAN DEFAULT true NOT NULL, antecedencia_expiracao_dias INT NOT NULL, fuso_horario VARCHAR(60) NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX unq_parametros_chave_escopo ON parametros_sistema (chave_escopo)'); $this->addSql('CREATE INDEX idx_parametros_instituicao ON parametros_sistema (instituicao_id)'); $this->addSql('ALTER TABLE parametros_sistema ADD CONSTRAINT fk_parametros_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("INSERT INTO parametros_sistema (instituicao_id, escopo, chave_escopo, limite_upload_mb, notificacao_interna, notificacao_email, antecedencia_expiracao_dias, fuso_horario, criado_em, atualizado_em) VALUES (NULL, 'GLOBAL', 'GLOBAL', 10, true, true, 7, 'America/Sao_Paulo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql('CREATE TABLE auditorias_parametros_sistema (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parametro_id INT NOT NULL, usuario_id INT NOT NULL, valores_anteriores JSON DEFAULT NULL, valores_novos JSON NOT NULL, alterado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_auditorias_parametro ON auditorias_parametros_sistema (parametro_id)'); $this->addSql('CREATE INDEX idx_auditorias_parametro_usuario ON auditorias_parametros_sistema (usuario_id)'); $this->addSql('ALTER TABLE auditorias_parametros_sistema ADD CONSTRAINT fk_auditorias_parametro FOREIGN KEY (parametro_id) REFERENCES parametros_sistema (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE auditorias_parametros_sistema ADD CONSTRAINT fk_auditorias_parametro_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE auditorias_parametros_sistema'); $this->addSql('DROP TABLE parametros_sistema'); }
}
