<?php

declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260818013000 extends AbstractMigration
{
    public function getDescription(): string { return 'Cria a tabela de escritórios regionais'; }
    public function up(Schema $schema): void { $this->addSql('CREATE TABLE escritorios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, instituicao_id INT NOT NULL, nome VARCHAR(150) NOT NULL, uf VARCHAR(2) NOT NULL, cidade VARCHAR(120) NOT NULL, endereco VARCHAR(255) DEFAULT NULL, ativo BOOLEAN DEFAULT true NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))'); $this->addSql('CREATE INDEX idx_escritorios_instituicao ON escritorios (instituicao_id)'); $this->addSql('CREATE UNIQUE INDEX unq_escritorios_instituicao_nome ON escritorios (instituicao_id, nome)'); $this->addSql('ALTER TABLE escritorios ADD CONSTRAINT fk_escritorios_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE escritorios'); }
}
