<?php

declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260818100000 extends AbstractMigration
{
    public function getDescription(): string { return 'Cria usuários e histórico de remanejamentos'; }
    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE usuarios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, instituicao_id INT NOT NULL, escritorio_id INT NOT NULL, nome VARCHAR(150) NOT NULL, email VARCHAR(180) NOT NULL, senha_hash VARCHAR(255) NOT NULL, perfil VARCHAR(20) NOT NULL, admin_global BOOLEAN DEFAULT false NOT NULL, ativo BOOLEAN DEFAULT true NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX unq_usuarios_email ON usuarios (email)'); $this->addSql('CREATE INDEX idx_usuarios_instituicao ON usuarios (instituicao_id)'); $this->addSql('CREATE INDEX idx_usuarios_escritorio ON usuarios (escritorio_id)');
        $this->addSql('ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_escritorio FOREIGN KEY (escritorio_id) REFERENCES escritorios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE remanejamentos_usuarios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usuario_id INT NOT NULL, escritorio_origem_id INT NOT NULL, escritorio_destino_id INT NOT NULL, remanejado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_remanejamentos_usuario ON remanejamentos_usuarios (usuario_id)'); $this->addSql('CREATE INDEX idx_remanejamentos_origem ON remanejamentos_usuarios (escritorio_origem_id)'); $this->addSql('CREATE INDEX idx_remanejamentos_destino ON remanejamentos_usuarios (escritorio_destino_id)');
        $this->addSql('ALTER TABLE remanejamentos_usuarios ADD CONSTRAINT fk_remanejamentos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE remanejamentos_usuarios ADD CONSTRAINT fk_remanejamentos_origem FOREIGN KEY (escritorio_origem_id) REFERENCES escritorios (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE remanejamentos_usuarios ADD CONSTRAINT fk_remanejamentos_destino FOREIGN KEY (escritorio_destino_id) REFERENCES escritorios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE remanejamentos_usuarios'); $this->addSql('DROP TABLE usuarios'); }
}
