<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260818004500 extends AbstractMigration
{
    public function getDescription(): string { return 'Cria a tabela de instituições'; }
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE instituicoes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(150) NOT NULL, sigla VARCHAR(20) NOT NULL, cnpj VARCHAR(14) DEFAULT NULL, ativo BOOLEAN DEFAULT TRUE NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX unq_instituicoes_sigla ON instituicoes (sigla)');
        $this->addSql('CREATE UNIQUE INDEX unq_instituicoes_cnpj ON instituicoes (cnpj)');
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE instituicoes'); }
}
