<?php

declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260818150000 extends AbstractMigration
{
    public function getDescription(): string { return 'Cria publicações e auditoria de transições editoriais'; }
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE publicacoes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo_conteudo_id INT NOT NULL, autor_id INT NOT NULL, instituicao_id INT NOT NULL, escritorio_id INT NOT NULL, aprovador_id INT DEFAULT NULL, titulo VARCHAR(150) NOT NULL, corpo TEXT NOT NULL, anexo_url VARCHAR(500) DEFAULT NULL, status VARCHAR(30) NOT NULL, justificativa_rejeicao VARCHAR(1000) DEFAULT NULL, publicar_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expirar_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_publicacoes_status ON publicacoes (status)'); $this->addSql('CREATE INDEX idx_publicacoes_instituicao ON publicacoes (instituicao_id)'); $this->addSql('CREATE INDEX idx_publicacoes_tipo ON publicacoes (tipo_conteudo_id)'); $this->addSql('CREATE INDEX idx_publicacoes_autor ON publicacoes (autor_id)'); $this->addSql('CREATE INDEX idx_publicacoes_escritorio ON publicacoes (escritorio_id)'); $this->addSql('CREATE INDEX idx_publicacoes_aprovador ON publicacoes (aprovador_id)');
        $this->addSql('ALTER TABLE publicacoes ADD CONSTRAINT fk_publicacoes_tipo FOREIGN KEY (tipo_conteudo_id) REFERENCES tipos_conteudo (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE publicacoes ADD CONSTRAINT fk_publicacoes_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE publicacoes ADD CONSTRAINT fk_publicacoes_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE publicacoes ADD CONSTRAINT fk_publicacoes_escritorio FOREIGN KEY (escritorio_id) REFERENCES escritorios (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE publicacoes ADD CONSTRAINT fk_publicacoes_aprovador FOREIGN KEY (aprovador_id) REFERENCES usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE transicoes_publicacoes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, publicacao_id INT NOT NULL, usuario_id INT NOT NULL, status_origem VARCHAR(30) NOT NULL, status_destino VARCHAR(30) NOT NULL, justificativa VARCHAR(1000) DEFAULT NULL, ocorrido_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_transicoes_publicacao ON transicoes_publicacoes (publicacao_id)'); $this->addSql('CREATE INDEX idx_transicoes_usuario ON transicoes_publicacoes (usuario_id)'); $this->addSql('ALTER TABLE transicoes_publicacoes ADD CONSTRAINT fk_transicoes_publicacao FOREIGN KEY (publicacao_id) REFERENCES publicacoes (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE transicoes_publicacoes ADD CONSTRAINT fk_transicoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE transicoes_publicacoes'); $this->addSql('DROP TABLE publicacoes'); }
}
