<?php

declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260818113000 extends AbstractMigration
{
    public function getDescription(): string { return 'Cria tipos de conteúdo e histórico de responsáveis'; }
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tipos_conteudo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, instituicao_id INT NOT NULL, responsavel_id INT NOT NULL, nome VARCHAR(150) NOT NULL, descricao VARCHAR(500) DEFAULT NULL, ativo BOOLEAN DEFAULT true NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX unq_tipos_conteudo_instituicao_nome ON tipos_conteudo (instituicao_id, nome)'); $this->addSql('CREATE INDEX idx_tipos_conteudo_instituicao ON tipos_conteudo (instituicao_id)'); $this->addSql('CREATE INDEX idx_tipos_conteudo_responsavel ON tipos_conteudo (responsavel_id)');
        $this->addSql('ALTER TABLE tipos_conteudo ADD CONSTRAINT fk_tipos_conteudo_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE tipos_conteudo ADD CONSTRAINT fk_tipos_conteudo_responsavel FOREIGN KEY (responsavel_id) REFERENCES usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE alteracoes_responsaveis_tipos_conteudo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo_conteudo_id INT NOT NULL, responsavel_anterior_id INT NOT NULL, responsavel_novo_id INT NOT NULL, alterado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_alteracoes_responsavel_tipo ON alteracoes_responsaveis_tipos_conteudo (tipo_conteudo_id)'); $this->addSql('CREATE INDEX idx_alteracoes_responsavel_anterior ON alteracoes_responsaveis_tipos_conteudo (responsavel_anterior_id)'); $this->addSql('CREATE INDEX idx_alteracoes_responsavel_novo ON alteracoes_responsaveis_tipos_conteudo (responsavel_novo_id)');
        $this->addSql('ALTER TABLE alteracoes_responsaveis_tipos_conteudo ADD CONSTRAINT fk_alteracoes_responsavel_tipo FOREIGN KEY (tipo_conteudo_id) REFERENCES tipos_conteudo (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE alteracoes_responsaveis_tipos_conteudo ADD CONSTRAINT fk_alteracoes_responsavel_anterior FOREIGN KEY (responsavel_anterior_id) REFERENCES usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE'); $this->addSql('ALTER TABLE alteracoes_responsaveis_tipos_conteudo ADD CONSTRAINT fk_alteracoes_responsavel_novo FOREIGN KEY (responsavel_novo_id) REFERENCES usuarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE alteracoes_responsaveis_tipos_conteudo'); $this->addSql('DROP TABLE tipos_conteudo'); }
}
